[versions]
# Gradle
versions = "0.42.0"

# Kotlin
kotlin = "1.7.20-Beta"

# Testing
kotest = "5.4.1"
mockk = "1.12.4"

[libraries]
# Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Testing
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
# Testing
testing = ["kotest-assertions", "kotest-junit"]

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }