[versions]
# Gradle
versions = "0.42.0"

# Kotlin
kotlin = "1.7.20-Beta"

[libraries]
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }