[versions]
# Gradle
versions = "0.42.0"

# Kotlin
kotlin = "1.7.20-Beta"
kotlin-coroutines = "1.6.4"

# Logging
slf4j = "2.0.0-beta1"
tinylog = "v3.0-SNAPSHOT"

# Networking
jmdns = "3.5.8"
netty = "5.0.0.Alpha4"
netty-contrib = "5.0.0.Alpha1"

# Testing
kotest = "5.4.1"
mockk = "1.12.4"

[libraries]
# Kotlin
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Logging
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
tinylog-api = { module = "com.github.tinylog-org.tinylog:tinylog-api", version.ref = "tinylog" }
tinylog-api-kotlin = { module = "com.github.tinylog-org.tinylog:tinylog-api-kotlin", version.ref = "tinylog" }
tinylog-impl = { module = "com.github.tinylog-org.tinylog:tinylog-impl", version.ref = "tinylog" }
tinylog-slf4j = { module = "com.github.tinylog-org.tinylog:slf4j-tinylog", version.ref = "tinylog" }

# Networking
jmdns = { module = "org.jmdns:jmdns", version.ref = "jmdns" }

# Testing
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-junit = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[bundles]
# Logging
tinylog = ["tinylog-impl", "tinylog-slf4j"]
tinylog-api = ["tinylog-api", "tinylog-api-kotlin", "slf4j"]

# Testing
kotest = ["kotest-assertions", "kotest-junit"]

[plugins]
# Kotlin
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

# Utility
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }