name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Gradle Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --no-daemon --scan

      - name: Extract CI Variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Upload detekt sarif report
        uses: github/codeql-action/upload-sarif@v1
        if: success() || failure()
        with:
            sarif_file: build/reports/merge.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ env.CI_REF_NAME_SLUG }}-${{ env.CI_SHA_SHORT }}
          path: build/distributions/*
