name: commit

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 'current'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Build
        run: pnpm exec commitlint --config config/commitlint/commitlint.config.js --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
