name: test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan
